// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtWiIa8nmircDhlpRLzEtAdSuOnBkHeDI',
    appId: '1:972334264189:web:014d9b220f1745d606a614',
    messagingSenderId: '972334264189',
    projectId: 'wealthwise-prototype',
    authDomain: 'wealthwise-prototype.firebaseapp.com',
    storageBucket: 'wealthwise-prototype.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATcYk-7eQHs-_CQnFQjUCJEYjBnU1iAJs',
    appId: '1:972334264189:android:575ad9860974e4f906a614',
    messagingSenderId: '972334264189',
    projectId: 'wealthwise-prototype',
    storageBucket: 'wealthwise-prototype.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUKNR_oWejCJ1ZZXytLZLN3PHNcSM2_Ak',
    appId: '1:972334264189:ios:a625e01241425ffa06a614',
    messagingSenderId: '972334264189',
    projectId: 'wealthwise-prototype',
    storageBucket: 'wealthwise-prototype.appspot.com',
    iosClientId: '972334264189-g7iju49i12uucff39sv3723953214ujt.apps.googleusercontent.com',
    iosBundleId: 'com.example.wealthwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUKNR_oWejCJ1ZZXytLZLN3PHNcSM2_Ak',
    appId: '1:972334264189:ios:a625e01241425ffa06a614',
    messagingSenderId: '972334264189',
    projectId: 'wealthwise-prototype',
    storageBucket: 'wealthwise-prototype.appspot.com',
    iosClientId: '972334264189-g7iju49i12uucff39sv3723953214ujt.apps.googleusercontent.com',
    iosBundleId: 'com.example.wealthwise',
  );
}
